// clean up database, also generated by gemini.
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// The recursive optimization engine
function optimizeRule(rule: any): any {
  // 1. Base cases: If it's a course or a special requirement, return it as-is.
  if (!rule || !rule.type) return null;
  if (rule.type !== 'and' && rule.type !== 'or') return rule;

  // 2. Recursively optimize all children first (Bottom-Up approach)
  if (Array.isArray(rule.operands)) {
    // Run the optimizer on every child, and remove any nulls
    rule.operands = rule.operands.map(optimizeRule).filter(Boolean);
  } else {
    return null; // If it's a logic node with no array, kill it.
  }

  // 3. GOLDEN RULE #1: Unwrap single items
  // If an AND or OR only has one child, the wrapper is useless. 
  // [AND (MAT021A)] becomes just MAT021A.
  if (rule.operands.length === 1) {
    return rule.operands;
  }

  // If there are no operands left, kill the node
  if (rule.operands.length === 0) {
    return null; 
  }

  // 4. GOLDEN RULE #2: Flatten nested identical operators
  // E.g., [AND (Course A), AND (Course B, Course C)] -> [AND (Course A, Course B, Course C)]
  const flattenedOperands = [];
  for (const child of rule.operands) {
    if (child.type === rule.type) {
      // The child is the exact same type as the parent! 
      // Bust it open and spread its contents into the parent's array.
      flattenedOperands.push(...child.operands);
    } else {
      // Different type, keep it intact
      flattenedOperands.push(child);
    }
  }
  
  rule.operands = flattenedOperands;

  return rule;
}

runOptimizer()
  .catch(console.error)
  .finally(() => prisma.$disconnect());

  async function runOptimizer() {
  console.log("Scanning database for redundant AST nodes...");
  const courses = await prisma.course.findMany();
  let updatedCount = 0;

  for (const course of courses) {
    if (!course.prerequisiteRules || !Array.isArray(course.prerequisiteRules) || course.prerequisiteRules.length === 0) continue;

    const oldRulesString = JSON.stringify(course.prerequisiteRules);

    // 1. THE IMPLICIT ROOT: Wrap the top-level array in a master AND node
    const implicitRoot = { 
      type: 'and', 
      operands: course.prerequisiteRules 
    };

    // 2. Run the optimizer on the ENTIRE tree at once
    const optimizedRoot = optimizeRule(implicitRoot);

    // 3. UNWRAP IT SAFELY back into an array for your database schema
    let finalRulesToSave: any[] = [];

    if (!optimizedRoot) {
      // The tree optimized down to nothing
      finalRulesToSave = [];
    } else if (optimizedRoot.type === 'and') {
      // It stayed an AND with multiple items. Strip the wrapper and save the clean array.
      finalRulesToSave = optimizedRoot.operands;
    } else {
      // It optimized all the way down to a SINGLE course or a SINGLE "OR" node. 
      // Wrap it in an array to maintain your implicit AND database schema.
      finalRulesToSave = [optimizedRoot];
    }
    const newRulesString = JSON.stringify(finalRulesToSave);

    if (oldRulesString !== newRulesString) {
        await new Promise(resolve => setTimeout(resolve, 50));
      try {
        await prisma.course.update({
          where: { id: course.id },
          data: { 
            prerequisiteRules: JSON.parse(newRulesString) 
          }
        });
        console.log(`Optimized ${course.code}`);
        updatedCount++;
      } catch (error) {
        // THE DETECTIVE: If the engine crashes, catch it and log the evidence!
        console.log(`\n💥 FATAL CRASH ON COURSE: ${course.code}`);
        console.log(`The Original AST was:`);
        console.dir(course.prerequisiteRules, { depth: null });
        console.log(`\nThe Optimizer tried to save:`);
        console.dir(finalRulesToSave, { depth: null });
        console.log(`----------------------------------------\n`);
        
        // We do NOT throw the error here, so the loop continues and fixes the rest!
      }
    }
  }

  console.log(`\nDone! Flattened the logic trees for ${updatedCount} courses.`);
}

runOptimizer()
  .catch(console.error)
  .finally(() => prisma.$disconnect());

