// run this in your browser at https://catalog.ucdavis.edu/courses-subject-code/[department]/, generated by Gemini
const scrapedCourses = [];
const courseBlocks = document.querySelectorAll('.courseblock');

courseBlocks.forEach(block => {
  try {
    // 1. Grab the Core Data
    const rawCode = block.querySelector('.detail-code')?.textContent.trim() || '';
    
    // The title has a leading "— " (and a non-breaking space), so we strip that out
    let rawTitle = block.querySelector('.detail-title')?.textContent.trim() || '';
    rawTitle = rawTitle.replace(/^[—\s\xA0]+/, ''); 

    // Extract just the integer from "(3 units)"
    const rawUnits = block.querySelector('.detail-hours_html')?.textContent || '';
    const units = parseInt(rawUnits.replace(/\D/g, '')) || 0;

    // 2. Find the Description
    // There are multiple 'courseblockextra' classes, so we loop to find the right one
    let description = '';
    const extraParagraphs = block.querySelectorAll('p.courseblockextra');
    extraParagraphs.forEach(p => {
      if (p.textContent.includes('Course Description:')) {
         description = p.textContent.replace('Course Description:', '').trim();
      }
    });

    // 3. Find the Prerequisites
    let prereqText = '';
    const prereqEl = block.querySelector('.detail-prerequisite');
    if (prereqEl) {
      prereqText = prereqEl.textContent.replace('Prerequisite(s):', '').trim();
    }

    // 4. Find the Grade Mode
    let grading = "Letter"; // Default
    const listItems = block.querySelectorAll('.toggle-content li');
    listItems.forEach(li => {
      if (li.textContent.includes('Grade Mode:')) {
        const mode = li.textContent.replace('Grade Mode:', '').trim();
        // Just standardizing it to match your Prisma Schema
        if (mode.includes('Pass/No Pass')) grading = "P/NP";
        else if (mode.includes('Letter')) grading = "Letter";
      }
    });

    // 5. Generate the Slug ("PHY 001B" -> "PHY001B")
    const slug = rawCode.replace(/\s+/g, '').toUpperCase();

    // 6. Push to our array
    if (rawCode) {
      scrapedCourses.push({
        code: rawCode,
        slug: slug,
        name: rawTitle,
        description: description,
        units: units,
        grading: grading,
        
        // I am saving the raw text here so you don't lose it.
        // We will need to convert this text into your JSON AST later!
        rawPrerequisitesText: prereqText, 
        prerequisiteRules: []
      });
    }
  } catch (error) {
    console.warn(`Skipped a course due to parsing error:`, error);
  }
});

// Output the final JSON array to the console!
console.log(JSON.stringify(scrapedCourses, null, 2));